name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update version.json
        run: |
          echo '{
            "version": "1.0.1",
            "changes": [
              "Добавлена новая функция A",
              "Исправлена ошибка B"
            ]
          }' > version.json

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "atvgo145@gmail.com"
          git config --local user.name "atvxgo"
          git add version.json
          git commit -m "Обновление version.json" || echo "Нет изменений"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/atvxgo/atvxgo.github.io.git HEAD:main
